# Generated by Django 6.0.2 on 2026-04-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineBbc', '0004_product_image1_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
